import type { KnowledgeNode } from "@/domain/knowledge-node/model";

function yamlString(value: string) {
  return JSON.stringify(value);
}

function yamlList(values: string[]) {
  return values.length
    ? values.map((value) => `  - ${yamlString(value)}`).join("\n")
    : "  []";
}

export function generateNodeMarkdown(node: KnowledgeNode) {
  const resources = node.resources.length
    ? node.resources
        .map(
          (resource) =>
            `- [${resource.title || resource.website}](${resource.url}) _(${resource.type})_`,
        )
        .join("\n")
    : "_No resources yet._";
  const relationships = node.relations.length
    ? node.relations
        .map((relation) => `- ${relation.type}: \`${relation.targetId}\``)
        .join("\n")
    : "_No relationships yet._";

  return `---
id: ${yamlString(node.id)}
title: ${yamlString(node.title)}
slug: ${yamlString(node.slug)}
archived: ${node.archived}
favorite: ${node.favorite}
sections:
${yamlList(node.sections)}
keywords:
${yamlList(node.keywords)}
tags:
${yamlList(node.tags)}
createdAt: ${yamlString(node.createdAt)}
updatedAt: ${yamlString(node.updatedAt)}
---

# ${node.title}

## Summary

${node.summary || "_No summary yet._"}

## Notes

${node.notes || "_No notes yet._"}

## Resources

${resources}

## Relationships

${relationships}
`;
}

export function generateGraphJson(nodes: KnowledgeNode[]) {
  return JSON.stringify(
    {
      version: 2,
      generatedAt: new Date().toISOString(),
      nodes,
    },
    null,
    2,
  );
}

function escapeTable(value: string) {
  return value
    .replace(/\|/g, "\\|")
    .replace(/\r?\n/g, " ")
    .trim();
}

function truncate(value: string, length = 100) {
  const clean = escapeTable(value);
  return clean.length > length ? `${clean.slice(0, length - 1)}…` : clean;
}

function encodeRepositoryPath(path: string) {
  return path.split("/").map(encodeURIComponent).join("/");
}

function uniqueByMarkdownPath(nodes: KnowledgeNode[]) {
  const unique = new Map<string, KnowledgeNode>();
  for (const node of [...nodes].sort((left, right) =>
    left.updatedAt.localeCompare(right.updatedAt),
  )) {
    unique.set(node.slug, node);
  }
  return [...unique.values()];
}

function nodeLink(node: KnowledgeNode, directory: string) {
  return `[${escapeTable(node.title)}](${encodeRepositoryPath(
    `${directory}/nodes/${node.slug}.md`,
  )})`;
}

function nodeTable(nodes: KnowledgeNode[], directory: string) {
  if (!nodes.length) return "_No topics in this collection yet._";
  return `| Topic | Summary | Tags | Updated |
| --- | --- | --- | --- |
${nodes
  .map((node) => {
    const summary = truncate(node.summary || node.notes || "Notes coming soon.");
    const tags = node.tags.length
      ? node.tags.map((tag) => `\`${escapeTable(tag)}\``).join(" ")
      : "—";
    return `| ${nodeLink(node, directory)} | ${summary} | ${tags} | ${new Date(
      node.updatedAt,
    ).toISOString().slice(0, 10)} |`;
  })
  .join("\n")}`;
}

export function generateKnowledgeReadme(
  nodes: KnowledgeNode[],
  directory = "knowledge",
) {
  const active = uniqueByMarkdownPath(
    nodes.filter((node) => !node.archived),
  );
  const sections = new Map<string, KnowledgeNode[]>();

  for (const node of active) {
    const memberships = node.sections.length ? node.sections : ["Unsorted"];
    for (const section of memberships) {
      sections.set(section, [...(sections.get(section) ?? []), node]);
    }
  }

  const sectionEntries = [...sections.entries()].sort(([left], [right]) =>
    left.localeCompare(right),
  );
  const sectionOverview = sectionEntries.length
    ? `| Section | Topics |
| --- | ---: |
${sectionEntries
  .map(
    ([section, sectionNodes]) =>
      `| ${escapeTable(section)} | ${sectionNodes.length} |`,
  )
  .join("\n")}`
    : "_No sections yet._";
  const body = sectionEntries
    .sort(([left], [right]) => left.localeCompare(right))
    .map(
      ([section, sectionNodes]) =>
        `<details open>
<summary><strong>${escapeTable(section)}</strong> · ${sectionNodes.length} ${
          sectionNodes.length === 1 ? "topic" : "topics"
        }</summary>

${nodeTable(
  sectionNodes.sort((left, right) => left.title.localeCompare(right.title)),
  directory,
)}

</details>`,
    )
    .join("\n\n");
  const favorites = active.filter((node) => node.favorite);
  const recent = [...active]
    .sort((left, right) => right.updatedAt.localeCompare(left.updatedAt))
    .slice(0, 8);
  const generatedAt = new Date().toISOString();

  return `<div align="center">

# 🧠 KnowlegeGraph

**A searchable, version-controlled map of everything you learn.**

![Knowledge nodes](https://img.shields.io/badge/knowledge_nodes-${active.length}-176b4d?style=flat-square)
![Sections](https://img.shields.io/badge/sections-${sectionEntries.length}-315f52?style=flat-square)
![Storage](https://img.shields.io/badge/storage-Markdown-d89b4a?style=flat-square)

</div>

> [!NOTE]
> This dashboard is generated by the KnowlegeGraph browser extension. IndexedDB
> is the offline-first working database; this repository provides readable
> Markdown, backup, and version history.

## Overview

${sectionOverview}

## ⭐ Favorites

${favorites.length ? nodeTable(favorites, directory) : "_No favorites yet._"}

## Explore by section

${body || "_No knowledge nodes have been synced yet._"}

## Recently updated

${nodeTable(recent, directory)}

---

<sub>Last synchronized ${generatedAt}. Generated automatically—edit knowledge in
the extension so local data and repository history stay consistent.</sub>
`;
}
