import type { KnowledgeNode } from "@/domain/knowledge-node/model";

function yamlString(value: string) {
  return JSON.stringify(value);
}

function yamlList(values: string[]) {
  return values.length
    ? values.map((value) => `  - ${yamlString(value)}`).join("\n")
    : "  []";
}

export function generateNodeMarkdown(node: KnowledgeNode) {
  const resources = node.resources.length
    ? node.resources
        .map(
          (resource) =>
            `- [${resource.title || resource.website}](${resource.url}) _(${resource.type})_`,
        )
        .join("\n")
    : "_No resources yet._";
  const relationships = node.relations.length
    ? node.relations
        .map((relation) => `- ${relation.type}: \`${relation.targetId}\``)
        .join("\n")
    : "_No relationships yet._";

  return `---
id: ${yamlString(node.id)}
title: ${yamlString(node.title)}
slug: ${yamlString(node.slug)}
archived: ${node.archived}
favorite: ${node.favorite}
sections:
${yamlList(node.sections)}
keywords:
${yamlList(node.keywords)}
tags:
${yamlList(node.tags)}
createdAt: ${yamlString(node.createdAt)}
updatedAt: ${yamlString(node.updatedAt)}
---

# ${node.title}

## Summary

${node.summary || "_No summary yet._"}

## Notes

${node.notes || "_No notes yet._"}

## Resources

${resources}

## Relationships

${relationships}
`;
}

export function generateGraphJson(nodes: KnowledgeNode[]) {
  return JSON.stringify(
    {
      version: 2,
      generatedAt: new Date().toISOString(),
      nodes,
    },
    null,
    2,
  );
}

export function generateKnowledgeReadme(nodes: KnowledgeNode[]) {
  const active = nodes.filter((node) => !node.archived);
  const sections = new Map<string, KnowledgeNode[]>();

  for (const node of active) {
    const memberships = node.sections.length ? node.sections : ["Unsorted"];
    for (const section of memberships) {
      sections.set(section, [...(sections.get(section) ?? []), node]);
    }
  }

  const body = [...sections.entries()]
    .sort(([left], [right]) => left.localeCompare(right))
    .map(
      ([section, sectionNodes]) =>
        `## ${section}\n\n${sectionNodes
          .sort((left, right) => left.title.localeCompare(right.title))
          .map((node) => `- [${node.title}](nodes/${node.slug}.md)`)
          .join("\n")}`,
    )
    .join("\n\n");

  return `# KnowlegeGraph

> Generated by the KnowlegeGraph browser extension. Local IndexedDB remains the
> primary database; this repository is a portable Markdown backup and history.

${active.length} active knowledge nodes.

${body || "_No knowledge nodes have been synced yet._"}
`;
}
