import { createHashRouter, Link, NavLink, Outlet, useParams } from "react-router";
import { RouterProvider } from "react-router/dom";
import { useState } from "react";
import { repositoryUrl } from "../lib/portal-data";
import { usePortalData, PortalDataProvider } from "./PortalDataContext";
import type { KnowledgeGraph, KnowledgeNode, PortalStats, SectionIndex } from "../types";
import { TopicList } from "../components/TopicList";
import { buildSectionIndex, derivedStats } from "../lib/portal-data";

function PortalShell() {
  const { nodes, sections, stats } = usePortalData();
  const sectionChips = [
    { name: "All", count: nodes.length, to: "/" },
    ...sections.map((section) => ({
      name: section.name,
      count: section.count,
      to: `/section/${encodeURIComponent(section.name)}`,
    })),
  ];

  return (
    <div className="portal-shell">
      <header className="site-header">
        <div className="masthead">
          <Link className="logo" to="/">
            <span aria-hidden="true" className="logo-mark">
              KG
            </span>
            <span className="logo-copy">
              <strong>KnowlegeGraph</strong>
              <small>Simple knowledge site</small>
            </span>
          </Link>
          <nav className="primary-nav" aria-label="Primary navigation">
            <NavLink end to="/">
              Topics
            </NavLink>
            <NavLink to="/timeline">Timeline</NavLink>
            <NavLink to="/stats">Stats</NavLink>
          </nav>
          <a className="github-link" href={repositoryUrl()} target="_blank" rel="noreferrer">
            GitHub
          </a>
        </div>
        <div className="utility-bar">
          <div className="section-links-mobile" aria-label="Sections">
            {Array.from({ length: 3 }).map((_, row) => (
              <div className="section-marquee" key={row}>
                <div className="section-marquee-track">
                  {[...sectionChips, ...sectionChips].map((section, index) => (
                    <Link
                      key={`${row}-${section.name}-${index}`}
                      className={section.name === "All" ? "active" : undefined}
                      to={section.to}
                    >
                      {section.name}
                      <span>{section.count}</span>
                    </Link>
                  ))}
                </div>
              </div>
            ))}
          </div>
          <div className="header-note">
            <span>{nodes.length}</span> topics
          </div>
        </div>
      </header>
      <main>
        <section className="page">
          <Outlet />
        </section>
        <footer>Generated by KnowlegeGraph · Markdown is the source of truth.</footer>
      </main>
    </div>
  );
}

function TopicHome() {
  const { nodes, sections, stats } = usePortalData();
  const [query, setQuery] = useState("");
  const recent = [...nodes]
    .sort((a, b) => b.updatedAt.localeCompare(a.updatedAt))
    .filter((node) => {
      const haystack = [
        node.title,
        node.summary,
        node.notes,
        node.sections.join(" "),
        node.tags.join(" "),
        node.keywords.join(" "),
        node.resources.map((resource) => resource.url).join(" "),
      ]
        .join(" ")
        .toLowerCase();
      return !query.trim() || haystack.includes(query.trim().toLowerCase());
    });
  return (
    <div className="home-page">
      <section className="home-intro">
        <div>
          <p className="eyebrow">Knowledge topics</p>
          <h1>Simple list of what you read.</h1>
        </div>
        <div className="intro-note">
          <p>A simple list of blogs, docs, and pages you want to keep in one place.</p>
          <input
            className="home-search"
            value={query}
            onChange={(event) => setQuery(event.target.value)}
            placeholder="Search topics, tags, or links..."
            aria-label="Search topics"
          />
          <div className="stats-inline">
            <span>
              <strong>{stats.topics}</strong> topics
            </span>
            <span>
              <strong>{stats.sections}</strong> sections
            </span>
            <span>
              <strong>{stats.resources}</strong> links
            </span>
          </div>
        </div>
      </section>

      <section className="collection-feed">
        <div className="collection-heading">
          <div>
            <p className="collection-label">The collection</p>
            <h2>All topics</h2>
          </div>
        </div>
        <TopicList nodes={recent.filter((node) => {
          const haystack = [
            node.title,
            node.summary,
            node.notes,
            node.sections.join(" "),
            node.tags.join(" "),
            node.keywords.join(" "),
            node.resources.map((resource) => resource.url).join(" "),
          ]
            .join(" ")
            .toLowerCase();
          return !query.trim() || haystack.includes(query.trim().toLowerCase());
        })} />
      </section>

      <aside className="collection-sections collection-sections-rail">
        <p className="collection-label">Sections</p>
        {sections.map((section) => (
          <Link key={section.name} to={`/section/${encodeURIComponent(section.name)}`}>
            <span>{section.name}</span>
            <small>{section.count}</small>
          </Link>
        ))}
      </aside>

    </div>
  );
}

function SectionRoute() {
  const { nodes } = usePortalData();
  const { name = "" } = useParams();
  const [query, setQuery] = useState("");
  const section = decodeURIComponent(name);
  const selected = nodes.filter((node) => node.sections.includes(section));
  const filtered = query.trim()
    ? selected.filter((node) =>
        [node.title, node.summary, node.tags.join(" "), node.keywords.join(" ")]
          .join(" ")
          .toLowerCase()
          .includes(query.trim().toLowerCase()),
      )
    : selected;

  return (
    <>
      <p className="breadcrumb">
        <Link to="/">Home</Link> / Sections / {section}
      </p>
      <div className="page-heading">
        <p className="eyebrow">Section</p>
        <h1 className="page-title">{section}</h1>
        <p className="lede">{filtered.length} topics in this section.</p>
      </div>
      <input
        className="home-search"
        value={query}
        onChange={(event) => setQuery(event.target.value)}
        placeholder="Search this section..."
        aria-label={`Search ${section}`}
      />
      <TopicList nodes={filtered} />
    </>
  );
}

function TimelineRoute() {
  const { nodes } = usePortalData();
  const months = [...nodes]
    .sort((a, b) => b.createdAt.localeCompare(a.createdAt))
    .reduce<Record<string, KnowledgeNode[]>>((result, node) => {
      const month = new Date(node.createdAt).toLocaleDateString(undefined, {
        month: "long",
        year: "numeric",
      });
      result[month] = [...(result[month] ?? []), node];
      return result;
    }, {});

  return (
    <>
      <div className="page-heading">
        <p className="eyebrow">Timeline</p>
        <h1 className="page-title">Reading history</h1>
        <p className="lede">A chronological index of when each topic was added.</p>
      </div>
      <div className="timeline">
        {Object.entries(months).map(([month, items]) => (
          <section key={month}>
            <h2>{month}</h2>
            <TopicList nodes={items ?? []} />
          </section>
        ))}
      </div>
    </>
  );
}

function StatsRoute() {
  const { nodes, stats } = usePortalData();
  const cards: Array<[string, string | number]> = [
    ["Topics", stats.topics],
    ["Sections", stats.sections],
    ["Links", stats.resources],
    ["Relationships", stats.relationships],
  ];
  return (
    <>
      <div className="page-heading">
        <p className="eyebrow">Stats</p>
        <h1 className="page-title">Library index</h1>
        <p className="lede">A quick look at the size and shape of the collection.</p>
      </div>
      <div className="metric-grid">
        {cards.map(([label, value]) => (
          <div key={label}>
            <strong>{value}</strong>
            <span>{label}</span>
          </div>
        ))}
      </div>
      <TopicList nodes={[...nodes].sort((a, b) => b.relations.length - a.relations.length)} />
    </>
  );
}

const router = createHashRouter([
  {
    path: "/",
    element: <PortalShell />,
    children: [
      { index: true, element: <TopicHome /> },
      { path: "section/:name", element: <SectionRoute /> },
      { path: "timeline", element: <TimelineRoute /> },
      { path: "stats", element: <StatsRoute /> },
    ],
  },
]);

export function PortalRouter({
  graph,
  sections,
  stats,
}: {
  graph: KnowledgeGraph;
  sections: SectionIndex["sections"];
  stats: PortalStats;
}) {
  const active = graph.nodes.filter((node) => !node.archived);
  return (
    <PortalDataProvider
      value={{
        nodes: active,
        sections: sections.length ? sections : buildSectionIndex(active),
        stats: stats ?? derivedStats(active),
      }}
    >
      <RouterProvider router={router} />
    </PortalDataProvider>
  );
}
